DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS listings;
DROP TABLE IF EXISTS tag_listings;
DROP TABLE IF EXISTS subcategory_list;



CREATE TABLE tags (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT UNIQUE
);

CREATE TABLE listings (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  url TEXT NOT NULL UNIQUE
);

CREATE TABLE tag_listings (
  listing_id INTEGER REFERENCES listings(id),
  tag_id INTEGER REFERENCES tags(id)
);

CREATE TABLE subcategory_list (
  tag_id INTEGER references tags(id),
  subcategory_to INTEGER references tags(id)
);